apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: &app-name ss-sa-go-worker-webhook
  namespace: test-a
  labels:
    app: *app-name
spec:
  retrySettings:
    maxRetries: 3
    retryInterval: "10s"
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: sa-go-worker-webhook