apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-go-worker-webhook
  namespace: test-a
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::992382474575:role/OIDCRoleGoWorkerWebHook"